name: Python bot CI

on:
  push:
    branches:
      - main
      - dev-ops-and-doc

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11.3"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm sync -d -G testing
        working-directory: tg-stonks

      - name: Run Tests
        run: |
          pdm run -v pytest tests
        working-directory: tg-stonks
